name: FRSP-Carta
on:
  push:
    branches: 
    - master
    - dev
  pull_request:
    branches: 
    - master

jobs:
  build:
    name: Build
    runs-on: [windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Setup MSBuild path
        uses: warrenbuckley/Setup-MSBuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2

      - name: Restore NuGet Packages
        run: nuget restore FRSP-LINQ.sln

      - name: Build FRSP-Carta
        run: msbuild FRSP-LINQ.sln /p:Configuration=Debug /p:DeployOnBuild=false
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1.0.0
        with:
          name: Carta-Release
          path: build/Release
